### ISSUE TITLE
Test source code for PEP8 conformance

### ISSUE THREAD

**Issue by robwoolley** [ros-infrastructure/superflore#305]
The CI tests currently fail to test for PEP8 conformance:

```
======================================================================
FAIL: Test source code for PEP8 conformance
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/nose/case.py", line 170, in runTest
    self.test(*self.arg)
  File "/home/runner/work/superflore/superflore/tests/test_code_format.py", line 54, in test_pep8
    assert p.returncode == 0, \
AssertionError: Command '/opt/hostedtoolcache/Python/3.10.15/x64/bin/python -m pycodestyle /home/runner/work/superflore/superflore/tests/../superflore --count' returned non-zero exit code '1'
```

Running the test manually shows:
```
(venv) rosuser@da759d65bbf0:~$ python -m pycodestyle superflore/superflore
superflore/superflore/generators/ebuild/gen_packages.py:159:80: E501 line too long (88 > 79 characters)
superflore/superflore/generators/ebuild/gen_packages.py:177:80: E501 line too long (99 > 79 characters)
superflore/superflore/generators/ebuild/gen_packages.py:212:80: E501 line too long (88 > 79 characters)
superflore/superflore/generators/ebuild/overlay_instance.py:99:80: E501 line too long (80 > 79 characters)
superflore/superflore/generators/buildstream/bst_element.py:149:80: E501 line too long (96 > 79 characters)
superflore/superflore/generators/buildstream/bst_element.py:207:80: E501 line too long (107 > 79 characters)
superflore/superflore/generators/buildstream/bst_element.py:213:80: E501 line too long (86 > 79 characters)
superflore/superflore/generators/buildstream/bst_element.py:222:80: E501 line too long (88 > 79 characters)
superflore/superflore/generators/buildstream/bst_element.py:255:80: E501 line too long (88 > 79 characters)
superflore/superflore/generators/buildstream/bst_element.py:258:80: E501 line too long (100 > 79 characters)
superflore/superflore/generators/buildstream/bst_element.py:278:80: E501 line too long (84 > 79 characters)
superflore/superflore/generators/buildstream/bst_element.py:280:80: E501 line too long (115 > 79 characters)
superflore/superflore/generators/buildstream/bst_element.py:315:80: E501 line too long (81 > 79 characters)
superflore/superflore/generators/buildstream/gen_packages.py:36:54: E251 unexpected spaces around keyword / parameter equals
superflore/superflore/generators/buildstream/gen_packages.py:36:56: E251 unexpected spaces around keyword / parameter equals
superflore/superflore/generators/buildstream/gen_packages.py:48:80: E501 line too long (97 > 79 characters)
superflore/superflore/generators/buildstream/gen_packages.py:68:18: E127 continuation line over-indented for visual indent
superflore/superflore/generators/buildstream/gen_packages.py:84:22: E127 continuation line over-indented for visual indent
superflore/superflore/generators/buildstream/gen_packages.py:106:16: E261 at least two spaces before inline comment
superflore/superflore/generators/buildstream/gen_packages.py:106:17: E262 inline comment should start with '# '
superflore/superflore/generators/buildstream/gen_packages.py:176:80: E501 line too long (80 > 79 characters)
superflore/superflore/generators/buildstream/gen_packages.py:180:80: E501 line too long (86 > 79 characters)
superflore/superflore/generators/buildstream/gen_packages.py:184:80: E501 line too long (81 > 79 characters)
superflore/superflore/generators/buildstream/gen_packages.py:188:80: E501 line too long (95 > 79 characters)
superflore/superflore/generators/buildstream/gen_packages.py:199:80: E501 line too long (84 > 79 characters)
superflore/superflore/generators/buildstream/ros_bst_repo.py:23:80: E501 line too long (83 > 79 characters)
superflore/superflore/generators/buildstream/run.py:44:80: E501 line too long (87 > 79 characters)
superflore/superflore/generators/buildstream/run.py:52:80: E501 line too long (82 > 79 characters)
superflore/superflore/generators/buildstream/run.py:56:80: E501 line too long (108 > 79 characters)
superflore/superflore/generators/buildstream/run.py:130:80: E501 line too long (80 > 79 characters)
superflore/superflore/generators/buildstream/run.py:135:80: E501 line too long (131 > 79 characters)
superflore/superflore/generators/buildstream/run.py:136:80: E501 line too long (98 > 79 characters)
superflore/superflore/generators/buildstream/run.py:152:80: E501 line too long (88 > 79 characters)
```

**Comment by robwoolley** [comment]
This will be addressed by https://github.com/ros-infrastructure/superflore/pull/332
