### ISSUE TITLE
traceback when running a 2nd time in a row

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/superflore#50]
Related to #49 lets talk about how repeated builds and temp files might work better.

```
$ superflore-gen-ebuilds --dry-run --ros-distro lunar
Cloning repo ros/ros-overlay into directory /tmp/YmpJJukOup...
Creating new branch gentoo-bot-djqaSqVPxv...

Symbolicly linking files from /tmp/YmpJJukOup/ros-lunar...
Traceback (most recent call last):
  File "/home/tfoote/work/github/ros-infrastructure/superflore/superflore/generators/ebuild/run.py", line 92, in main
    link_existing_files(args.ros_distro)
  File "/home/tfoote/work/github/ros-infrastructure/superflore/superflore/generators/ebuild/run.py", line 43, in link_existing_files
    os.symlink(dir_fmt.format(overlay.repo_dir, mode), './ros-' + mode)
FileExistsError: [Errno 17] File exists: '/tmp/YmpJJukOup/ros-lunar' -> './ros-lunar'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tfoote/work/github/ros-infrastructure/superflore/sfvenv/bin/superflore-gen-ebuilds", line 11, in <module>
    load_entry_point('superflore==0.0.0', 'console_scripts', 'superflore-gen-ebuilds')()
  File "/home/tfoote/work/github/ros-infrastructure/superflore/superflore/generators/ebuild/run.py", line 93, in main
    except os.FileExistsError:
AttributeError: module 'os' has no attribute 'FileExistsError'
(sfvenv) tfoote@snowman:~/work/github/ros-infrastructure/superflore Last: [1] (36s Seconds)
$ ll
total 88
drwxrwxr-x 11 tfoote tfoote  4096 Aug  1 16:30 ./
drwxrwxr-x 22 tfoote tfoote  4096 Aug  1 16:05 ../
-rw-rw-r--  1 tfoote tfoote  9849 Aug  1 16:27 abb_driver-None.tar.gz
-rw-rw-r--  1 tfoote tfoote  1388 Aug  1 16:27 abb-None.tar.gz
drwxrwxr-x  4 tfoote tfoote  4096 Aug  1 16:30 build/
drwxrwxr-x  2 tfoote tfoote  4096 Aug  1 16:30 dist/
drwxrwxr-x  8 tfoote tfoote  4096 Aug  1 16:05 .git/
-rw-rw-r--  1 tfoote tfoote   109 Aug  1 16:05 .gitignore
-rw-rw-r--  1 tfoote tfoote 11358 Aug  1 16:05 LICENSE
-rw-rw-r--  1 tfoote tfoote   370 Aug  1 16:05 README.md
drwxrwxr-x  4 tfoote tfoote  4096 Aug  1 16:27 recipes-ros-indigo/
lrwxrwxrwx  1 tfoote tfoote    33 Aug  1 16:27 recipes-ros-lunar -> /tmp/WEHvSOMIka/recipes-ros-lunar/
drwxrwxr-x  2 tfoote tfoote  4096 Aug  1 16:05 repoman_docker/
lrwxrwxrwx  1 tfoote tfoote    25 Aug  1 16:08 ros-lunar -> /tmp/kAuPBiPoJb/ros-lunar/
-rwxrwxr-x  1 tfoote tfoote  1312 Aug  1 16:05 setup.py*
drwxrwxr-x  6 tfoote tfoote  4096 Aug  1 16:28 sfvenv/
drwxrwxr-x  4 tfoote tfoote  4096 Aug  1 16:07 superflore/
drwxrwxr-x  2 tfoote tfoote  4096 Aug  1 16:06 superflore.egg-info/
drwxrwxr-x  2 tfoote tfoote  4096 Aug  1 16:05 tests/
-rw-rw-r--  1 tfoote tfoote   295 Aug  1 16:05 .travis.yml
(sfvenv) tfoote@snowman:~/work/github/ros-infrastructure/superflore Last: [0] (0s Seconds)
$ rm -rf /tmp/kAuPBiPoJb/ros-lunar/ ros-lunar
```

**Comment by allenh1** [comment]
@tfoote This was a regression that happened in order to support Python 2 and 3, but I dropped 2 because the git pull request system doesn't work with 2 apparently (though, oddly, you can pip install it for python 2).

I'll fix this.
